export const AGENT_GUIDE_MARKDOWN = [
  "# Constitutional Map AI: Guide for AI Agents",
  "",
  "This document is for browser-based AI agents and assistants using the public web app.",
  "",
  "The application lets you explore constitutional text from 190+ countries in a 3D semantic map. A point usually represents one constitutional article or a similar legal unit.",
  "",
  "## What you can do reliably",
  "",
  "- Select countries from the world map or the control panel to load their points into the atlas.",
  "- Inspect article details by clicking points in the 3D view or search results.",
  "- Use two different search modes depending on the task.",
  "- Export result sets from the export modal.",
  "- Generate shared-view links to preserve a specific atlas state and pass it to another user or agent.",
  "",
  "## The two search modes",
  "",
  "### 1. Keyword search",
  "",
  "Use keyword search when you need literal matches in the constitutional text.",
  "",
  "Good use cases:",
  "",
  "- finding exact words or phrases such as `freedom of speech`",
  "- using Boolean logic such as `AND`, `OR`, quotes, and parentheses",
  "- checking whether a constitution uses a specific legal term",
  "",
  "Notes:",
  "",
  "- this mode is the right choice for exact language, phrase matching, and structured textual queries",
  "- advanced keyword queries can use Boolean operators and grouping",
  "- results are ranked full-text matches, not semantic paraphrases",
  "",
  "### 2. Semantic search",
  "",
  "Use semantic search when you need conceptually similar passages even if they do not share the same wording.",
  "",
  "Good use cases:",
  "",
  "- finding articles about judicial independence without requiring those exact words",
  "- retrieving passages about decentralization, emergency rule, or social rights phrased in different ways",
  "- exploring a legal idea before you know the precise vocabulary used in the corpus",
  "",
  "Notes:",
  "",
  "- this mode is the right choice for concepts, themes, and paraphrased ideas",
  "- English queries usually work best against the corpus, but the UI also accepts other languages",
  "- results are retrieved by conceptual similarity rather than literal term overlap",
  "",
  "## Exporting results",
  "",
  "Search panels and the combined search card support export.",
  "",
  "Available export formats:",
  "",
  "- JSON",
  "- CSV",
  "- XML",
  "- XLSX",
  "- Markdown",
  "- HTML",
  "",
  "If your environment cannot download files, use the export modal's `Copy` action instead of `Download`.",
  "",
  "Clipboard export works for:",
  "",
  "- JSON",
  "- CSV",
  "- XML",
  "- Markdown",
  "- HTML",
  "",
  "HTML export produces a standalone document with a simple results table, which can be useful when another browser tool expects an HTML document instead of plain text.",
  "",
  "Important limitation:",
  "",
  "- XLSX requires file download support and cannot be copied through the clipboard action",
  "",
  "## Shared views",
  "",
  "Use the Share action when you need to preserve context across sessions, chats, or agents.",
  "",
  "A shared view can capture:",
  "",
  "- selected countries",
  "- camera state",
  "- active search context",
  "- title, observation, and optional author metadata",
  "",
  "Preferred workflow:",
  "",
  "1. Set up the atlas view you want.",
  "2. Generate a shared view link.",
  "3. Pass that link to another user or agent.",
  "4. Re-open the link later to restore the same analytical context.",
  "",
  "## Recommended agent workflow",
  "",
  "1. Select a country set or preset relevant to the question.",
  "2. Start with semantic search if the request is conceptual.",
  "3. Switch to keyword search if you need exact terms, exact phrases, or Boolean logic.",
  "4. Open promising results to inspect the full constitutional text.",
  "5. Export or copy the result set if you need to move the data into another tool.",
  "6. Generate a shared view link if the state needs to be preserved.",
  "",
  "## Limits to keep in mind",
  "",
  "- The browser UI is the supported surface described here. This guide does not imply repository or API access.",
  "- Search results are aids for exploration, not a substitute for checking the full constitutional text.",
  "- If legal accuracy matters, inspect the full article text and verify against official constitutional sources.",
  "",
].join("\n");
