"""ISO 3166-1 country code mappings and region data for the TCA pipeline.

Each entry: (alpha3, alpha2, name, region, sub_region)
Source: ISO 3166-1 + UN M49 region classification.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class CountryInfo:
    alpha3: str
    alpha2: str
    name: str
    region: str
    sub_region: str


# fmt: off
_ENTRIES: list[tuple[str, str, str, str, str]] = [
    ("AFG", "AF", "Afghanistan",                        "Asia",    "Southern Asia"),
    ("ALB", "AL", "Albania",                            "Europe",  "Southern Europe"),
    ("DZA", "DZ", "Algeria",                            "Africa",  "Northern Africa"),
    ("AND", "AD", "Andorra",                            "Europe",  "Southern Europe"),
    ("AGO", "AO", "Angola",                             "Africa",  "Sub-Saharan Africa"),
    ("ATG", "AG", "Antigua and Barbuda",                "Americas","Caribbean"),
    ("ARG", "AR", "Argentina",                          "Americas","South America"),
    ("ARM", "AM", "Armenia",                            "Asia",    "Western Asia"),
    ("AUS", "AU", "Australia",                          "Oceania", "Australia and New Zealand"),
    ("AUT", "AT", "Austria",                            "Europe",  "Western Europe"),
    ("AZE", "AZ", "Azerbaijan",                         "Asia",    "Western Asia"),
    ("BHS", "BS", "Bahamas",                            "Americas","Caribbean"),
    ("BHR", "BH", "Bahrain",                            "Asia",    "Western Asia"),
    ("BGD", "BD", "Bangladesh",                         "Asia",    "Southern Asia"),
    ("BRB", "BB", "Barbados",                           "Americas","Caribbean"),
    ("BLR", "BY", "Belarus",                            "Europe",  "Eastern Europe"),
    ("BEL", "BE", "Belgium",                            "Europe",  "Western Europe"),
    ("BLZ", "BZ", "Belize",                             "Americas","Central America"),
    ("BEN", "BJ", "Benin",                              "Africa",  "Sub-Saharan Africa"),
    ("BTN", "BT", "Bhutan",                             "Asia",    "Southern Asia"),
    ("BOL", "BO", "Bolivia",                            "Americas","South America"),
    ("BIH", "BA", "Bosnia and Herzegovina",             "Europe",  "Southern Europe"),
    ("BWA", "BW", "Botswana",                           "Africa",  "Sub-Saharan Africa"),
    ("BRA", "BR", "Brazil",                             "Americas","South America"),
    ("BRN", "BN", "Brunei",                             "Asia",    "South-Eastern Asia"),
    ("BGR", "BG", "Bulgaria",                           "Europe",  "Eastern Europe"),
    ("BFA", "BF", "Burkina Faso",                       "Africa",  "Sub-Saharan Africa"),
    ("BDI", "BI", "Burundi",                            "Africa",  "Sub-Saharan Africa"),
    ("CPV", "CV", "Cabo Verde",                         "Africa",  "Sub-Saharan Africa"),
    ("KHM", "KH", "Cambodia",                           "Asia",    "South-Eastern Asia"),
    ("CMR", "CM", "Cameroon",                           "Africa",  "Sub-Saharan Africa"),
    ("CAN", "CA", "Canada",                             "Americas","Northern America"),
    ("CAF", "CF", "Central African Republic",           "Africa",  "Sub-Saharan Africa"),
    ("TCD", "TD", "Chad",                               "Africa",  "Sub-Saharan Africa"),
    ("CHL", "CL", "Chile",                              "Americas","South America"),
    ("CHN", "CN", "China",                              "Asia",    "Eastern Asia"),
    ("COL", "CO", "Colombia",                           "Americas","South America"),
    ("COM", "KM", "Comoros",                            "Africa",  "Sub-Saharan Africa"),
    ("COD", "CD", "Congo (Dem. Rep.)",                  "Africa",  "Sub-Saharan Africa"),
    ("COG", "CG", "Congo (Rep.)",                       "Africa",  "Sub-Saharan Africa"),
    ("CRI", "CR", "Costa Rica",                         "Americas","Central America"),
    ("CIV", "CI", "Côte d'Ivoire",                      "Africa",  "Sub-Saharan Africa"),
    ("HRV", "HR", "Croatia",                            "Europe",  "Southern Europe"),
    ("CUB", "CU", "Cuba",                               "Americas","Caribbean"),
    ("CYP", "CY", "Cyprus",                             "Asia",    "Western Asia"),
    ("CZE", "CZ", "Czechia",                            "Europe",  "Eastern Europe"),
    ("DNK", "DK", "Denmark",                            "Europe",  "Northern Europe"),
    ("DJI", "DJ", "Djibouti",                           "Africa",  "Sub-Saharan Africa"),
    ("DMA", "DM", "Dominica",                           "Americas","Caribbean"),
    ("DOM", "DO", "Dominican Republic",                 "Americas","Caribbean"),
    ("ECU", "EC", "Ecuador",                            "Americas","South America"),
    ("EGY", "EG", "Egypt",                              "Africa",  "Northern Africa"),
    ("SLV", "SV", "El Salvador",                        "Americas","Central America"),
    ("GNQ", "GQ", "Equatorial Guinea",                  "Africa",  "Sub-Saharan Africa"),
    ("ERI", "ER", "Eritrea",                            "Africa",  "Sub-Saharan Africa"),
    ("EST", "EE", "Estonia",                            "Europe",  "Northern Europe"),
    ("SWZ", "SZ", "Eswatini",                           "Africa",  "Sub-Saharan Africa"),
    ("ETH", "ET", "Ethiopia",                           "Africa",  "Sub-Saharan Africa"),
    ("FJI", "FJ", "Fiji",                               "Oceania", "Melanesia"),
    ("FIN", "FI", "Finland",                            "Europe",  "Northern Europe"),
    ("FRA", "FR", "France",                             "Europe",  "Western Europe"),
    ("GAB", "GA", "Gabon",                              "Africa",  "Sub-Saharan Africa"),
    ("GMB", "GM", "Gambia",                             "Africa",  "Sub-Saharan Africa"),
    ("GEO", "GE", "Georgia",                            "Asia",    "Western Asia"),
    ("DEU", "DE", "Germany",                            "Europe",  "Western Europe"),
    ("GHA", "GH", "Ghana",                              "Africa",  "Sub-Saharan Africa"),
    ("GRC", "GR", "Greece",                             "Europe",  "Southern Europe"),
    ("GRD", "GD", "Grenada",                            "Americas","Caribbean"),
    ("GTM", "GT", "Guatemala",                          "Americas","Central America"),
    ("GIN", "GN", "Guinea",                             "Africa",  "Sub-Saharan Africa"),
    ("GNB", "GW", "Guinea-Bissau",                      "Africa",  "Sub-Saharan Africa"),
    ("GUY", "GY", "Guyana",                             "Americas","South America"),
    ("HTI", "HT", "Haiti",                              "Americas","Caribbean"),
    ("HND", "HN", "Honduras",                           "Americas","Central America"),
    ("HUN", "HU", "Hungary",                            "Europe",  "Eastern Europe"),
    ("ISL", "IS", "Iceland",                            "Europe",  "Northern Europe"),
    ("IND", "IN", "India",                              "Asia",    "Southern Asia"),
    ("IDN", "ID", "Indonesia",                          "Asia",    "South-Eastern Asia"),
    ("IRN", "IR", "Iran",                               "Asia",    "Southern Asia"),
    ("IRQ", "IQ", "Iraq",                               "Asia",    "Western Asia"),
    ("IRL", "IE", "Ireland",                            "Europe",  "Northern Europe"),
    ("ISR", "IL", "Israel",                             "Asia",    "Western Asia"),
    ("ITA", "IT", "Italy",                              "Europe",  "Southern Europe"),
    ("JAM", "JM", "Jamaica",                            "Americas","Caribbean"),
    ("JPN", "JP", "Japan",                              "Asia",    "Eastern Asia"),
    ("JOR", "JO", "Jordan",                             "Asia",    "Western Asia"),
    ("KAZ", "KZ", "Kazakhstan",                         "Asia",    "Central Asia"),
    ("KEN", "KE", "Kenya",                              "Africa",  "Sub-Saharan Africa"),
    ("KIR", "KI", "Kiribati",                           "Oceania", "Micronesia"),
    ("PRK", "KP", "Korea (North)",                      "Asia",    "Eastern Asia"),
    ("KOR", "KR", "Korea (South)",                      "Asia",    "Eastern Asia"),
    ("KWT", "KW", "Kuwait",                             "Asia",    "Western Asia"),
    ("KGZ", "KG", "Kyrgyzstan",                         "Asia",    "Central Asia"),
    ("LAO", "LA", "Laos",                               "Asia",    "South-Eastern Asia"),
    ("LVA", "LV", "Latvia",                             "Europe",  "Northern Europe"),
    ("LBN", "LB", "Lebanon",                            "Asia",    "Western Asia"),
    ("LSO", "LS", "Lesotho",                            "Africa",  "Sub-Saharan Africa"),
    ("LBR", "LR", "Liberia",                            "Africa",  "Sub-Saharan Africa"),
    ("LBY", "LY", "Libya",                              "Africa",  "Northern Africa"),
    ("LIE", "LI", "Liechtenstein",                      "Europe",  "Western Europe"),
    ("LTU", "LT", "Lithuania",                          "Europe",  "Northern Europe"),
    ("LUX", "LU", "Luxembourg",                         "Europe",  "Western Europe"),
    ("MDG", "MG", "Madagascar",                         "Africa",  "Sub-Saharan Africa"),
    ("MWI", "MW", "Malawi",                             "Africa",  "Sub-Saharan Africa"),
    ("MYS", "MY", "Malaysia",                           "Asia",    "South-Eastern Asia"),
    ("MDV", "MV", "Maldives",                           "Asia",    "Southern Asia"),
    ("MLI", "ML", "Mali",                               "Africa",  "Sub-Saharan Africa"),
    ("MLT", "MT", "Malta",                              "Europe",  "Southern Europe"),
    ("MHL", "MH", "Marshall Islands",                   "Oceania", "Micronesia"),
    ("MRT", "MR", "Mauritania",                         "Africa",  "Northern Africa"),
    ("MUS", "MU", "Mauritius",                          "Africa",  "Sub-Saharan Africa"),
    ("MEX", "MX", "Mexico",                             "Americas","Central America"),
    ("FSM", "FM", "Micronesia",                         "Oceania", "Micronesia"),
    ("MDA", "MD", "Moldova",                            "Europe",  "Eastern Europe"),
    ("MCO", "MC", "Monaco",                             "Europe",  "Western Europe"),
    ("MNG", "MN", "Mongolia",                           "Asia",    "Eastern Asia"),
    ("MNE", "ME", "Montenegro",                         "Europe",  "Southern Europe"),
    ("MAR", "MA", "Morocco",                            "Africa",  "Northern Africa"),
    ("MOZ", "MZ", "Mozambique",                         "Africa",  "Sub-Saharan Africa"),
    ("MMR", "MM", "Myanmar",                            "Asia",    "South-Eastern Asia"),
    ("NAM", "NA", "Namibia",                            "Africa",  "Sub-Saharan Africa"),
    ("NRU", "NR", "Nauru",                              "Oceania", "Micronesia"),
    ("NPL", "NP", "Nepal",                              "Asia",    "Southern Asia"),
    ("NLD", "NL", "Netherlands",                        "Europe",  "Western Europe"),
    ("NZL", "NZ", "New Zealand",                        "Oceania", "Australia and New Zealand"),
    ("NIC", "NI", "Nicaragua",                          "Americas","Central America"),
    ("NER", "NE", "Niger",                              "Africa",  "Sub-Saharan Africa"),
    ("NGA", "NG", "Nigeria",                            "Africa",  "Sub-Saharan Africa"),
    ("MKD", "MK", "North Macedonia",                    "Europe",  "Southern Europe"),
    ("NOR", "NO", "Norway",                             "Europe",  "Northern Europe"),
    ("OMN", "OM", "Oman",                               "Asia",    "Western Asia"),
    ("PAK", "PK", "Pakistan",                           "Asia",    "Southern Asia"),
    ("PLW", "PW", "Palau",                              "Oceania", "Micronesia"),
    ("PAN", "PA", "Panama",                             "Americas","Central America"),
    ("PNG", "PG", "Papua New Guinea",                   "Oceania", "Melanesia"),
    ("PRY", "PY", "Paraguay",                           "Americas","South America"),
    ("PER", "PE", "Peru",                               "Americas","South America"),
    ("PHL", "PH", "Philippines",                        "Asia",    "South-Eastern Asia"),
    ("POL", "PL", "Poland",                             "Europe",  "Eastern Europe"),
    ("PRT", "PT", "Portugal",                           "Europe",  "Southern Europe"),
    ("QAT", "QA", "Qatar",                              "Asia",    "Western Asia"),
    ("ROU", "RO", "Romania",                            "Europe",  "Eastern Europe"),
    ("RUS", "RU", "Russia",                             "Europe",  "Eastern Europe"),
    ("RWA", "RW", "Rwanda",                             "Africa",  "Sub-Saharan Africa"),
    ("KNA", "KN", "Saint Kitts and Nevis",              "Americas","Caribbean"),
    ("LCA", "LC", "Saint Lucia",                        "Americas","Caribbean"),
    ("VCT", "VC", "Saint Vincent and the Grenadines",   "Americas","Caribbean"),
    ("WSM", "WS", "Samoa",                              "Oceania", "Polynesia"),
    ("SMR", "SM", "San Marino",                         "Europe",  "Southern Europe"),
    ("STP", "ST", "Sao Tome and Principe",              "Africa",  "Sub-Saharan Africa"),
    ("SAU", "SA", "Saudi Arabia",                       "Asia",    "Western Asia"),
    ("SEN", "SN", "Senegal",                            "Africa",  "Sub-Saharan Africa"),
    ("SRB", "RS", "Serbia",                             "Europe",  "Southern Europe"),
    ("SYC", "SC", "Seychelles",                         "Africa",  "Sub-Saharan Africa"),
    ("SLE", "SL", "Sierra Leone",                       "Africa",  "Sub-Saharan Africa"),
    ("SGP", "SG", "Singapore",                          "Asia",    "South-Eastern Asia"),
    ("SVK", "SK", "Slovakia",                           "Europe",  "Eastern Europe"),
    ("SVN", "SI", "Slovenia",                           "Europe",  "Southern Europe"),
    ("SLB", "SB", "Solomon Islands",                    "Oceania", "Melanesia"),
    ("SOM", "SO", "Somalia",                            "Africa",  "Sub-Saharan Africa"),
    ("ZAF", "ZA", "South Africa",                       "Africa",  "Sub-Saharan Africa"),
    ("SSD", "SS", "South Sudan",                        "Africa",  "Sub-Saharan Africa"),
    ("ESP", "ES", "Spain",                              "Europe",  "Southern Europe"),
    ("LKA", "LK", "Sri Lanka",                          "Asia",    "Southern Asia"),
    ("SDN", "SD", "Sudan",                              "Africa",  "Northern Africa"),
    ("SUR", "SR", "Suriname",                           "Americas","South America"),
    ("SWE", "SE", "Sweden",                             "Europe",  "Northern Europe"),
    ("CHE", "CH", "Switzerland",                        "Europe",  "Western Europe"),
    ("SYR", "SY", "Syria",                              "Asia",    "Western Asia"),
    ("TWN", "TW", "Taiwan",                             "Asia",    "Eastern Asia"),
    ("TJK", "TJ", "Tajikistan",                         "Asia",    "Central Asia"),
    ("TZA", "TZ", "Tanzania",                           "Africa",  "Sub-Saharan Africa"),
    ("THA", "TH", "Thailand",                           "Asia",    "South-Eastern Asia"),
    ("TLS", "TL", "Timor-Leste",                        "Asia",    "South-Eastern Asia"),
    ("TGO", "TG", "Togo",                               "Africa",  "Sub-Saharan Africa"),
    ("TON", "TO", "Tonga",                              "Oceania", "Polynesia"),
    ("TTO", "TT", "Trinidad and Tobago",                "Americas","Caribbean"),
    ("TUN", "TN", "Tunisia",                            "Africa",  "Northern Africa"),
    ("TUR", "TR", "Turkey",                             "Asia",    "Western Asia"),
    ("TKM", "TM", "Turkmenistan",                       "Asia",    "Central Asia"),
    ("TUV", "TV", "Tuvalu",                             "Oceania", "Polynesia"),
    ("UGA", "UG", "Uganda",                             "Africa",  "Sub-Saharan Africa"),
    ("UKR", "UA", "Ukraine",                            "Europe",  "Eastern Europe"),
    ("ARE", "AE", "United Arab Emirates",               "Asia",    "Western Asia"),
    ("GBR", "GB", "United Kingdom",                     "Europe",  "Northern Europe"),
    ("USA", "US", "United States",                      "Americas","Northern America"),
    ("URY", "UY", "Uruguay",                            "Americas","South America"),
    ("UZB", "UZ", "Uzbekistan",                         "Asia",    "Central Asia"),
    ("VUT", "VU", "Vanuatu",                            "Oceania", "Melanesia"),
    ("VEN", "VE", "Venezuela",                          "Americas","South America"),
    ("VNM", "VN", "Vietnam",                            "Asia",    "South-Eastern Asia"),
    ("YEM", "YE", "Yemen",                              "Asia",    "Western Asia"),
    ("ZMB", "ZM", "Zambia",                             "Africa",  "Sub-Saharan Africa"),
    ("ZWE", "ZW", "Zimbabwe",                           "Africa",  "Sub-Saharan Africa"),
]
# fmt: on

COUNTRIES: list[CountryInfo] = [CountryInfo(*e) for e in _ENTRIES]

_BY_ALPHA3 = {c.alpha3: c for c in COUNTRIES}
_BY_ALPHA2 = {c.alpha2: c for c in COUNTRIES}
_BY_NAME   = {c.name.lower(): c for c in COUNTRIES}


def by_alpha3(code: str) -> CountryInfo | None:
    return _BY_ALPHA3.get(code.upper())


def by_alpha2(code: str) -> CountryInfo | None:
    return _BY_ALPHA2.get(code.upper())


def by_name(name: str) -> CountryInfo | None:
    return _BY_NAME.get(name.lower())
